### ISSUE TITLE
npm install complains

### ISSUE THREAD

**Issue by matkoniecz** [juliuste/bilkom#13]
I followed recommended installation process and got some warnings

```
$ npm install --save bilkom
npm WARN saveError ENOENT: no such file or directory, open '/home/mateusz/Desktop/tmp/bilkom/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/mateusz/Desktop/tmp/bilkom/package.json'
npm WARN bilkom No description
npm WARN bilkom No repository field.
npm WARN bilkom No README data
npm WARN bilkom No license field.
```

**Comment by juliuste** [comment]
`--save` tries to add the package to your `package.json`, I'm assuming that there is none in your directory, hence the errors. Not sure if this is bad on the package's part, though, since this is rather normal behaviour.

**Comment by matkoniecz** [comment]
>  since this is rather normal behaviour.

In that case I am closing. I have no experience with npm and "npm WARN bilkom" suggested to me that problem caused by bilkom.

I will look at npm bugtracker, if they have less than 1000 open issues I will report this interface issue.

EDIT: From what I see at https://github.com/npm/cli and https://npm.community/ they have no bug tracker and handle reports by dumping them on a forum, so there is no point in spending time on reporting issues.

**Comment by matkoniecz** [comment]
From what I see at https://github.com/npm/cli and https://npm.community/ they have no bug tracker and handle reports by dumping it on forum, so there is no point in spending time on reporting issues.

**Comment by juliuste** [comment]
Could it be that the directory you were trying to install the package in was also called `bilkom`? Because as far as I know, the displayed error name will be the current directory.

**Comment by matkoniecz** [comment]
Yes, from looking at it - there is a complaint about `/home/mateusz/Desktop/tmp/bilkom/package.json` file.
