### ISSUE TITLE
unclear "Ask them for permission before using this module in production"

### ISSUE THREAD

**Issue by matkoniecz** [juliuste/bilkom#9]
Is it possible to specify who should be contacted? PKP is a maze of various companies (and maybe not PKP should be contacted but whoever operates bilkom)?

**Comment by matkoniecz** [comment]
Also, is my understanding of this that it is OK to use this API without permission from anybody - but without many requests and without expecting any uptime is OK?

**Comment by juliuste** [comment]
> Also, is my understanding of this that it is OK to use this API without permission from anybody - but without many requests and without expecting any uptime is OK?

As far as I know, scraping is a legal gray area, but you should be fine if you just send requests "for personal use". *Disclaimer: This info is not legally binding, I am not a lawyer.*

> Is it possible to specify who should be contacted? PKP is a maze of various companies (and maybe not PKP should be contacted but whoever operates bilkom)?

You should probably contact [bilkom](https://beta.bilkom.pl/kontakt), even though I'm not sure if they'd allow you to use this specific third-party module 😄 But give it a try, if you want, and let me know what they answered.

*PS: For legal reasons, I can't answer this very specifically here, if you want to know more or want to hear my personal "opinion" on how you can use this, contact me via [e-mail](mailto:mail@juliustens.eu) 😉*

**Comment by matkoniecz** [comment]
I think that it is now answered as well as it can be and I have no good ideas how to improve readme, so I will close this one.
